# ----
# Site

title: Learnings
url: "https://pages.github.corp.ebay.com"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentation for AI Driven Bug Classification And Triaging.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Learnings
  links:
    - https://github.corp.ebay.com/manperuma/learnings

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-relative-links

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 1200
          height: 2000
  - scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release
        
types:
  - minor
  - major
