name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send POST Request
      run: |
          curl -X GET \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
          -d '{"build_status": "started", "branch": "${{ github.ref_name }}", "commit": "${{ github.sha }}"}' \
          https://infinite-sands-52519-06605f47cb30.herokuapp.com/home?${{ github.sha }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Build
      uses: actions/jekyll-build-pages@v1
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
